name: Create a new Milestone

on:
  issues:
    types: [opened, edited]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Milestone Actions
        if: github.event.issue.labels[0].name == 'milestone'
        uses: kyoyadmoon/milestone-actions@v1.0.0
        with:
          title: github.event.issue.title
          # An optional description for the milestone
          # description: # optional
          # An optional timestamp for due date of the milestone
          # due_on: # optional
        env:
          GITHUB_TOKEN: "${{ secrets.RANDEV_SCRUM_APP_PEM }}"
