name: Create a new Milestone

on:
  issues:
    types: [opened]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create Milestone'
        if: github.event.issue.labels[0].name == 'milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@master"
        with:
          title: github.event.issue.title
          description: github.event.issue.body
        env:
          GITHUB_TOKEN: "${{ secrets.RANDEV_SCRUM_APP_PEM }}"
