name: Create a new Milestone

on:
  issues:
    types: [opened]

jobs:
  newMilestone:
    if: github.event.issue.labels[0].name == 'milestone'
    runs-on: ubuntu-latest
    steps:
      - name: Create the milestone
        uses: julbme/gh-action-manage-milestone@v1
        with:
          title: github.event.issue.title
          state: open
          description: github.event.issue.body
        env:
          GITHUB_TOKEN: ${{ secrets.RANDEV_SCRUM_APP_PEM }}
