# Este worflow creara una nueva milestone cuando se detecte una nueva issue creada con 
# el label de milestone. El objetivo es manejar las milestones como Historias de Usuario
# dentro del marco de trabajo de SCRUM y poder gestionarlo facilmente desde un Project de 
# GitHub como el siguiente: https://github.com/orgs/Randev-ar/projects/24/views/2

name: Create a new Milestone

on:
  issues:
    types: [opened]

jobs:
  createMilestone:
    if: github.event.issue.labels[0].name == 'milestone'
    runs-on: ubuntu-latest
    steps:
      - name: Milestone Actions
        id: createmilestone
        uses: kyoyadmoon/milestone-actions@v1.0.0
        with:
          title: "${{ github.event.issue.title }}"
          description: "${{ github.event.issue.body }}" # An optional description
          # due_on: # An optional timestamp for due date of the milestone
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          
      - name: echo Milestone number
        run: echo ${{ steps.createmilestone.outputs.number }}

      - name: echo Milestone id
        run: echo ${{ steps.createmilestone.outputs.id }}

      - name: echo Milestone html_url
        run: echo ${{ steps.createmilestone.outputs.html_url }}
