name: Create a new Milestone

on:
  issues:
    types: [opened]

jobs:

  generate:
    if: github.event.issue.labels[0].name == 'milestone'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop

      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: 'Create new milestone'
        id: create-milestone
        uses: kyoyadmoon/milestone-actions@v1.0.0
        with:
          title: "${github.event.issue.title}"
          description: ${{ github.event.issue.body }}
        env:
          GITHUB_TOKEN: "${{ secrets.RANDEV_SCRUM_APP_PEM }}"

      - name: echo Milestone number
        run: echo ${{ steps.create-milestone.outputs.number }}

      - name: echo Milestone id
        run: echo ${{ steps.create-milestone.outputs.id }}

      - name: echo Milestone html_url
        run: echo ${{ steps.create-milestone.outputs.html_url }}
