name: Create a new Milestone

on:
  issues:
    types: [opened]

jobs:
  generate:
    if: github.event.issue.labels[0].name == 'milestone'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: 'Create new milestone'
        id: createmilestone
        uses: "WyriHaximus/github-action-create-milestone@v1"
        with:
          title: github.event.issue.title
        env:
          GITHUB_TOKEN: "${{ secrets.RANDEV_SCRUM_APP_PEM }}"
