name: Print event

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - develop

jobs:
  print:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: dump-github-context
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
