# ISO Langusge Codes: https://cloud.google.com/translate/docs/languages  
name: Translate README

on:
  push:
    paths:
      - 'README.md'
jobs:
  translating:
    name: 💬 Translate Readme
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: 🇬🇧 English
        uses: dephraiim/translate-readme@main
        with:
          LANG: en
